# conda build . --package-format conda

{% set name = "plotnn" %}
{% set version = "0.1.0" %}
{% set python_min = "3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dd31f6dcb0378e23119313a50d3390ca883d5f5454d43ef842c490794e5dc83d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - plotnn
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/CharlesShan-hub/plotnn
  summary: Modified from https://github.com/HarisIqbal88/PlotNeuralNet
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - CharlesShan-hub
